version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net

#  webapp:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#    networks:
#      - net
#    ports:
#      - '8000:8000'
#    volumes:
#      - .:/code
#      - static_volume:/code/static

networks:
  net:

volumes:
  postgres-data:
  static_volume:
  db_data: